# Generated by Django 4.1.2 on 2022-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.DateField(max_length=30)),
                ('fecha', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
